// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Conntrack = newAsset("conntrack.c", "255370edee2ef60565bf2d3c684bea4990445b76b2c9e02efeefa7239d2b543e")
