// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = newAsset("http.c", "644be98045de7388f61012b21471c8998c47ea3c942b93f41eb675619ea6d3d9")
