// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = newAsset("tracer.c", "837639fb75c5306918e1f7086c33208240fcd6aa66b46350fbf85794ffc2a9fe")
